
id = "WFRus"
name = "WFRus"
description = "Русификатор WEBFISHING"
version = "0.0.5"
homepage = "https://github.com/xllifi/WFRus"
author = "xllifi"

icon = "icon.png"
readme = "README.md"
changelog = "CHANGELOG.md"

[project]
csharp = "./WFRusCS/WFRus.csproj"
godot = "./WFRusGD/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"
