
id = "WFRus"
name = "WFRus"
description = "Русификатор WEBFISHING"
version = "0.0.1"
homepage = "https://steamcommunity.com"
author = "xllifi"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./WFRusCS/WFRus.csproj"
godot = "./WFRusGD/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"
